// saga
export const REGISTER_USER = 'REGISTER_USER';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FACEBOOK = 'LOGIN_USER_FACEBOOK';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_EVENTS = 'GET_EVENTS';

export const DELETE_EVENT = 'DELETE_EVENT';

export const POST_EVENT = 'POST_EVENT';

export const CLEAN_EVENTS_WHEN_LOGOUT = 'CLEAN_EVENTS_WHEN_LOGOUT';

export const CLEAN_USERS_ERROR = 'CLEAN_USERS_ERROR';

export const DELETE_SHARED_USER = 'DELETE_SHARED_USER';

export const GET_USERS = 'GET_USERS';

export const ADD_SHARED_USER = 'ADD_SHARED_USER';

// redux

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const CLEAN_USERS_ERROR_SUCCESS = 'CLEAN_USERS_ERROR_SUCCESS';

export const ADD_SHARED_USER_SUCCESS = 'ADD_SHARED_USER_SUCCESS';
export const ADD_SHARED_USER_ERROR = 'ADD_SHARED_USER_ERROR';

export const DELETE_SHARED_USER_SUCCESS = 'DELETE_SHARED_USER_SUCCESS';
export const DELETE_SHARED_USER_ERROR = 'DELETE_SHARED_USER_ERROR';

export const CLEAN_EVENTS_WHEN_LOGOUT_SUCCESS = 'CLEAN_EVENTS_WHEN_LOGOUT_SUCCESS';

export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
export const POST_EVENT_ERROR = 'POST_EVENT_ERROR';

export const DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR';

