// saga
export const REGISTER_USER = 'REGISTER_USER';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FACEBOOK = 'LOGIN_USER_FACEBOOK';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_EVENTS = 'GET_EVENTS';

// redux

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

